name: build-all-configs
on: [push]
jobs:
  build-on-osx-for-osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - id: configure-cmake
      run: cmake -S . -B build -DDJINNI_WITH_OBJC=ON -DDJINNI_STATIC_LIB=ON -G Xcode
    - id: build-release
      run: cmake --build build --parallel $(sysctl -n hw.ncpu) --config Release
    - id: install-files
      run: cmake --build build --parallel $(sysctl -n hw.ncpu) --config Release --target install -- DESTDIR=zinstall_root
    - id: list-installed-files
      run: cd build/zinstall_root && du -a | tail -r | | awk -F ' ' '{print $2}'
    - id: test-file-list
      run: cd build/zinstall_root && diff -u ../../test/objc_list.txt <(du -a | tail -r | awk -F ' ' '{print $2}')
